name: skeleton
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.2
  hive: ^2.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  dropdown_button2: ^2.1.3
  count_stepper: ^0.0.4
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.0
  dotted_border: ^2.0.0+3
  path_provider: ^2.1.1
  flutter_pin_code_fields: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
